2009-09-18	Joel Sherrill <joel.sherrill@oarcorp.com>
	* check_endof: Improve to only pay attention to .exe and .ralf files.

diff --git a/rtems/check_endof b/rtems/check_endof
--- a/rtems/check_endof
+++ b/rtems/check_endof
@@ -12,10 +12,16 @@ while :
 do
   for f in `ls -1 ${logdir}* | grep -v info$`
   do
-    grep "END OF" $f >/dev/null
-    if [ $? -ne 0 ] ; then
-      echo "ERROR - $f did not appear to complete execution"
-    fi
+    case ${f} in
+      *.exe|*.ralf) 
+        grep "END OF" $f >/dev/null
+        if [ $? -ne 0 ] ; then
+          echo "ERROR - $f did not appear to complete execution"
+        fi
+        ;;
+      *)
+        ;;
+     esac
   done
 
   if [ X${1} = X ] ; then
