2011-08-21	Jie Liu <lj8175@gmail.com>
	* gcc/rtems_gcj_init.c: New file for rtems/gcj testing.
	* gcc/Makefile.rtems_gcjinit: The Makefile for
	gcc/rtems_gcj_init.c
	* gcc/rundeja: Add options for libjava test.
	* gcc/test_driver: Add GCJ options.
	* gcc/do_one: Add GCJ build and test options.

diff --git a/gcc/do_one b/gcc/do_one
--- a/gcc/do_one
+++ b/gcc/do_one
@@ -10,10 +10,12 @@
 #   - building Objective-C (multilib)      - 6m45.532s
 #   - building Ada (multilib)              - ?
 #   - building Go (multilib)               - ?
+#   - building GCJ (multilib)              - ?
 #   - Running GCC Test Suite (sis)         - 122m47.289s
 #   - Running Objective-C Test Suite (sis) - ?
 #   - Running ACAT           (sis)         - ?
 #   - Running Go Test Suite  (sis)         - ?
+#   - Running GCJ Test Suite  (sis)        - ?
 #
 # Computer Info
 #   Fedora 14 on Intel Core2 Duo Q6600 (4 core) @ 2.40GHz w/ 4GB RAM
@@ -51,6 +53,9 @@ do_ada=no
 # Build the GCC Go language cross compiler.
 do_gccgo=no
 	do_gccgo_multilib=yes
+# Build the GCC Java language cross compiler.
+do_gcj=no
+	do_gcj_multilib=yes
 # Build RTEMS for a particular CPU/BSP combination
 do_rtems=no
 # Which test suites do we attempt
@@ -59,6 +64,7 @@ run_objctests=no
 run_acats=no
 run_gccgotests=no
 run_libgotests=no
+run_libjavatests=no
 # Do we send email to gcc-testresults with the test results?
 do_mail=yes
 # Are we noisy when running?
@@ -69,8 +75,8 @@ usage()
 {
 cat <<EOF
 do_one [options] CPU BSP
-  -A - binutils, stage 1, C++, C/C++ multilib, Ada, GCC Go, RTEMS
-  -T - run GCC, Ada and GCC Go tests
+  -A - binutils, stage 1, C++, C/C++ multilib, Ada, GCC Go, GCJ, RTEMS
+  -T - run GCC, Ada, GCC Go and GCJ tests
   -b - install binutils (from source or copy installed RPM contents)
   -D - install gdb (from source or copy installed RPM contents)
   -n - native compiler
@@ -79,6 +85,7 @@ do_one [options] CPU BSP
   -m -   do not build multilib
   -a - stage 2 Ada compiler
   -G - stage 2 GCC Go compiler
+  -J - stage 2 GCC Java compiler
   -r - build RTEMS
   -g - run GCC C/C++ tests
   -C - run ACATS
@@ -89,6 +96,7 @@ do_one [options] CPU BSP
   -P - Run Objective-C Tests
   -o - run GCC Go tests
   -t - run libgo tests
+  -j - run libjava tests
 EOF
 }
 
@@ -117,6 +125,7 @@ do
            do_multilib="yes"
            do_ada="yes"
            do_gccgo="yes"
+           do_gcj="yes"
            do_objc="yes"
            do_rtems="yes"
            ;;
@@ -138,6 +147,7 @@ do
         # Stage 2 arguments
         a) do_ada=`toggle ${do_ada}` ;;
         G) do_gccgo=`toggle ${do_gccgo}` ;;
+        J) do_gcj=`toggle ${do_gcj}` ;;
         # Build RTEMS
         r) do_rtems=`toggle ${do_rtems}` ;;
         # Testsuites to run
@@ -149,6 +159,7 @@ do
         P) run_objctests=`toggle ${do_objc}` ;;
         o) run_gccgotests=`toggle ${run_gccgotests}` ;;
         t) run_libgotests=`toggle ${run_libgotests}` ;;
+        j) run_libjavatests=`toggle ${run_libjavatests}` ;;
         *) fatal ;;
     esac
 done
@@ -196,32 +207,46 @@ if [ ${do_gccgo} = "yes" ] ; then
   esac
 fi
 
+# Which CPUs do not support GCJ
+if [ ${do_gcj} = "yes" ] ; then
+  case ${cpu} in
+    avr|h8300|m32c)
+      do_gcj=no
+      echo ${cpu} does not support GCJ
+      ;;
+    *);;
+  esac
+fi
+
 # When verbose, print settings
 if [ ${verbose} = yes ] ; then
-  echo "Target        : " ${cpu}
-  echo "BSP           : " ${bsp}
-  echo "Binutils      : " ${do_binutils}
-  echo "GDB           : " ${do_gdb}
-  echo "Build Native  : " ${do_native}
-  echo "Build Stage 1 : " ${do_stage1}
-  echo "  C++         : " ${do_cxx}
-  echo "  Multilib    : " ${do_multilib}
-  echo "Stage 2       : " ${do_ada}
-  echo "  Objective-C : " ${do_objc}
-  echo "  Ada         : " ${do_ada}
-  echo "  Multilib    : " ${do_ada_multilib}
-  echo "  GCC Go      : " ${do_gccgo}
-  echo "  Multilib    : " ${do_gccgo_multilib}
-  echo "Build RTEMS   : " ${do_rtems}
-  echo "Run GCC Tests : " ${run_gcctests}
-  echo "Run ObjC Tests: " ${run_objctests}
-  echo "Run ACATS     : " ${run_acats}
-  echo "Run Go Tests  : " ${run_gccgotests}
-  echo "Do libgo Tests: " ${run_libgotests}
-  echo "Email Tests   : " ${do_mail}
-  echo "Native GCC    : " `type gcc`
-  echo "PATH          : " ${PATH}
-  echo "Clean up      : " ${do_cleanup}
+  echo "Target          : " ${cpu}
+  echo "BSP             : " ${bsp}
+  echo "Binutils        : " ${do_binutils}
+  echo "GDB             : " ${do_gdb}
+  echo "Build Native    : " ${do_native}
+  echo "Build Stage 1   : " ${do_stage1}
+  echo "  C++           : " ${do_cxx}
+  echo "  Multilib      : " ${do_multilib}
+  echo "Stage 2         : " ${do_ada}
+  echo "  Objective-C   : " ${do_objc}
+  echo "  Ada           : " ${do_ada}
+  echo "  Multilib      : " ${do_ada_multilib}
+  echo "  GCC Go        : " ${do_gccgo}
+  echo "  Go Multilib   : " ${do_gccgo_multilib}
+  echo "  GCJ           : " ${do_gcj}
+  echo "  GCJ Multilib  : " ${do_gccgcj_multilib}
+  echo "Build RTEMS     : " ${do_rtems}
+  echo "Run GCC Tests   : " ${run_gcctests}
+  echo "Run ObjC Tests  : " ${run_objctests}
+  echo "Run ACATS       : " ${run_acats}
+  echo "Run Go Tests    : " ${run_gccgotests}
+  echo "Do libgo Tests  : " ${run_libgotests}
+  echo "Do libjava Tests: " ${run_libjavatests}
+  echo "Email Tests     : " ${do_mail}
+  echo "Native GCC      : " `type gcc`
+  echo "PATH            : " ${PATH}
+  echo "Clean up        : " ${do_cleanup}
 fi
 
 # Should the user have specified a CPU and/or BSP?
@@ -229,7 +254,8 @@ needBSP=no
 needCPU=no
 
 if [ ${do_binutils} = yes -o ${do_gdb} = yes -o \
-     ${do_stage1} = yes -o ${do_ada} = yes -o ${do_gccgo} = yes ] ; then
+     ${do_stage1} = yes -o ${do_ada} = yes -o \
+     ${do_gccgo} = yes -o ${do_gcj} = yes ] ; then
   needCPU=yes
 fi
 
@@ -238,8 +264,14 @@ if [ ${do_native} = yes -a ${do_gccgo} = yes ] ; then
   do_cxx=yes
 fi
 
+if [ ${do_native} = yes -a ${do_gcj} = yes ] ; then
+  echo "Warning! GCJ requires native C++ to build."
+  do_cxx=yes
+fi
+
 if [ ${do_rtems} = yes -o ${run_gcctests} = yes -o \
-     ${run_acats} = yes -o ${run_gccgotests} = yes ] ; then
+     ${run_acats} = yes -o ${run_gccgotests} = yes -o \
+     ${run_libjavatests} = yes ] ; then
   needBSP=yes
   needCPU=yes
   if [ x${bsp} = x ] ; then
@@ -926,5 +958,87 @@ fi
 
 if [ ${do_gccgo} = "yes" ] ; then 
   test ${do_cleanup} = "yes" && rm -rf b-${cpu}-go
+fi
+exit 0
+
+##### Build a GCJ compiler now that we have a cross installed
+j_gcj()
+{
+  if [ X${1} = X ] ; then
+    echo Usage: $0 TARGET_CPU
+    exit 1
+  fi
+  TARGET=${1}-rtems${RTEMS_VERSION}
+
+  if [ ! -d ${INSTALL} ] ; then
+    echo ${INSTALL} does not exist
+    exit 1
+  fi
+
+  if [ ${verbose} = yes ] ; then
+    echo "Cross GCC ==>" `type ${TARGET}-gcc`
+  fi
+
+  if [ ${do_gcj_multilib} = yes ] ; then
+     gcj_multilib="--enable-multilib"
+  else
+     gcj_multilib="--disable-multilib"
+  fi
+
+  case ${TARGET} in
+    i386*) GOFLAGS="-march=i486" ;;
+    *)     GOFLAGS="" ;;
+  esac
+#    CFLAGS_FOR_TARGET=-B${BSP_INSTALL}/${TARGET}/${BSP_BUILT}/lib/
+
+  ${GCCDIR}/configure \
+   ${GCC_EXTRA_ARGS} \
+   CFLAGS_FOR_TARGET="-B${BSP_INSTALL}/${TARGET}/${BSP_BUILT}/lib/ ${GOFLAGS}" \
+     --enable-threads=rtems --with-gnu-as ${gcj_multilib} \
+     --with-gnu-ld --disable-newlib  --verbose \
+     --with-system-zlib --disable-nls \
+     --enable-version-specific-runtime-libs \
+     --with-host-libstdcxx=-static-libstdc++ \
+     --enable-languages=c,c++,java --target=$TARGET --prefix=$INSTALL &&
+  make ${MAKEJOBS} &&
+  make install
+  status=$?
+  if [ $status -ne 0 ] ; then
+    echo "Failed building GCJ"
+  fi
+  exit $status
+}
+
+gcj_fail="no"
+if [ ${do_gcj} = "yes" ] ; then 
+  echo "Building Stage 2 cross GCC Java compiler for ${1} ..."
+  (cd ${BASEDIR} && \
+   rm -rf b-${cpu}-gcj && \
+   mkdir  b-${cpu}-gcj && \
+   cd b-${cpu}-gcj && \
+   time j_gcj ${cpu} >${LOGDIR}/${cpu}-gcj.log 2>&1 && cd ..) || \
+     gcj_fail="yes"
+else
+  echo Skipping GCC Java compiler for ${cpu}
+fi
+
+##### Do the libjava tests
+if [ $a ${run_libjavatests} = "yes" -a \
+     -d ${BASEDIR}/b-${cpu}-gcj -a ${gcj_fail} = "no" ] ; then
+  echo "Running libjava DejaGNU tests..."
+  cd ${BASEDIR}/b-${cpu}-gcj || exit 1
+  time sh -x ${SCRIPTDIR}/gcc/rundeja ${bsp} libjava \
+    >${LOGDIR}/${cpu}-libjavatests-${bsp}.log 2>&1
+
+  RDIR=${RESULTSDIR}/${TARGET}-${bsp}/`date +%Y-%m-%d-%H-%M-%S`
+  mkdir -p ${RDIR}
+  cp ${TARGET}-${bsp}/libjava/testsuite/libjava-all.log \
+    ${TARGET}-${bsp}/libjava/testsuite/libjava-all.sum ${RDIR}
+else
+  echo Skipping libjava DejaGNU tests for ${cpu}/${bsp}
+fi
+
+if [ ${do_gcj} = "yes" ] ; then 
+  test ${do_cleanup} = "yes" && rm -rf b-${cpu}-gcj
 fi
 exit 0
