2009-07-30	Joel Sherrill <joel.sherrill@rtems.org>
	* do_one: Set parameters for qemu.
	* rundeja: Correct script name for qemu (now qemu-rtems).
	* test_driver: Abort if gcc_update fails.
	* testsuite/ada/acats/Makefile.rtems: Correct script invocations
	to reflect new sim-scripts.
	* testsuite/ada/acats/run_all_rtems.sh: Use full path to RTEMS_SETTINGS.
	* ChangeLog: New file.

diff --git a/gcc/test_driver b/gcc/test_driver
--- a/gcc/test_driver
+++ b/gcc/test_driver
@@ -55,6 +55,10 @@ update_gcc()
   cd ${GCCDIR}
   if [ -d .svn ] ; then
     ./contrib/gcc_update
+    if [ $? -ne 0 ] ; then
+      echo "Update of GCC Failed."
+      exit 1 
+    fi
   fi
 }
 
