2009-09-09	Joel Sherrill <joel.sherrill@OARcorp.com>
	* VERSIONS-COVERAGE: Add support for running coverage on 4.8 and 4.9.
	This was used to produce baseline data for comparison purposes.
	* rtems-48-20090909.diff, rtems-49-20090909.diff: New files.

diff --git a/rtems-coverage/VERSIONS-COVERAGE b/rtems-coverage/VERSIONS-COVERAGE
--- a/rtems-coverage/VERSIONS-COVERAGE
+++ b/rtems-coverage/VERSIONS-COVERAGE
@@ -2,8 +2,16 @@
 BASEDIR=${HOME}/test-gcc
 
 RTEMS_VERSION=4.10
+case ${RTEMS_VERSION} in
+  4.8)  RTEMSDIR=${BASEDIR}/rtems-48 ;;
+  4.9)  RTEMSDIR=${BASEDIR}/rtems-49 ;;
+  4.10) RTEMSDIR=${BASEDIR}/rtems ;;
+  *)
+    echo "ERROR -- UNKNOWN RTEMS VERSION ${RTEMS_VERSION}"
+    exit 1
+    ;;
+esac
 
-RTEMSDIR=${BASEDIR}/rtems
 LOGDIR=${BASEDIR}/log
 
 # These symbols mark the range of the code block we are analyzing.
