2009-07-20	Joel Sherrill <joel.sherrill@oarcorp.com>
	* gdb-sim-run.in: Do not create log if interactive.

diff --git a/sim-scripts/gdb-sim-run.in b/sim-scripts/gdb-sim-run.in
--- a/sim-scripts/gdb-sim-run.in
+++ b/sim-scripts/gdb-sim-run.in
@@ -100,10 +100,10 @@ args=$*
 
 if [ ${interactive} = "yes" ] ; then
   defaultLimit=0
-fi
-
-if [ ! -d ${logdir} ] ; then
-  mkdir $logdir || fatal "could not create log directory ($logdir)"
+else
+  if [ ! -d ${logdir} ] ; then
+    mkdir $logdir || fatal "could not create log directory ($logdir)"
+  fi
 fi
 
 ### Set BSP defaults.  If BSP does not have default, it will override
