2009-01-20	Joel Sherrill <joel.sherrill@oarcorp.com>
	* Makefile, edb7312.in, gdb-sim-run.in, gdb-sim.in, h8sim.in,
	jmr3904.in, m32csim.in, m32rsim.in, psim.in, simsh.in, sis.in,
	skyeye-support: Find run or gdb along PATH. Check for multiple RTEMS
	versions so there is only one version of the script. Default the
	simulator name so the BSP specific files do not have to do as much.

diff --git a/sim-scripts/gdb-sim-run.in b/sim-scripts/gdb-sim-run.in
--- a/sim-scripts/gdb-sim-run.in
+++ b/sim-scripts/gdb-sim-run.in
@@ -90,9 +90,20 @@ args=$*
 bspRunFatal="no"
 bspGeneratesDeviceTree="no"
 bspSupportsSystemVIPC="no"
+bspUsesGDBSimulator="yes"
+
+for v in 4.10 4.9 4.8 4.7 ""
+do
+  type @CPU_TARGET@-rtems${v}-run >/dev/null 2>&1
+  if [ $? -eq 0 ] ; then
+    defaultRUN=@CPU_TARGET@-rtems${v}-run
+    break
+  fi
+done
+
+runBSP=${defaultRUN}
 
 rtemsVersion=`echo ${progname} | sed -e 's/@BSP@-//' -e 's/-gdb//'`
-RUN=@CPU_TARGET@-rtems${rtemsVersion}-run
 
 ###################################################################
 ###################################################################
@@ -106,6 +117,13 @@ if [ ${bspSupportsSystemVIPC} = "no" -a ${use_sysv_ipc} = "yes"  ]; then
   echo "Simulator does not support System V IPC."
   exit 1
 fi
+
+if [ X${runBSP} = X ] ; then
+  echo "Unable to find a way to run @CPU_TARGET@/@BSP@"
+  exit 1
+fi
+
+test ${verbose} = "yes" && echo Using ${runBSP}
 
 ## These are faults any BSP may generate.  They are common to RTEMS.
 checkGenericFaults()
@@ -200,7 +218,7 @@ do
 
   ## Some BSPs must generate device trees to provide to the simulator
   if [ ${bspGeneratesDeviceTree} = "yes" ] ; then
-    bspGenerateDeviceTree ${baseToRun}
+    bspGenerateDeviceTree ${baseToRun} >${bspTreeFile}
     if [ ${generate_tree_and_exit} = "yes" ] ; then
       echo "Device tree generated and in ${bspTreeFile}"
       exit 0
diff --git a/sim-scripts/gdb-sim.in b/sim-scripts/gdb-sim.in
--- a/sim-scripts/gdb-sim.in
+++ b/sim-scripts/gdb-sim.in
@@ -13,7 +13,26 @@ trap "test_exit 1" 1 2 3 13 14 15
 
 progname=${0##*/}        # fast basename hack for ksh, bash
 rtemsVersion=`echo ${progname} | sed -e 's/@BSP@-//' -e 's/gdb-//'`
-GDB=@CPU_TARGET@-rtems${rtemsVersion}-gdb
+
+for v in 4.10 4.9 4.8 4.7 ""
+do
+  type @CPU_TARGET@-rtems${v}-gdb >/dev/null 2>&1
+  if [ $? -eq 0 ] ; then
+    GDB=@CPU_TARGET@-rtems${v}-gdb
+    break
+  fi
+  if [ X${GDB} = X ] ; then
+    echo "Unable to find a GDB for @CPU_TARGET@ along your PATH"
+    exit 1
+  fi
+
+  test ${verbose} = "yes" && echo Using ${GDB}
+done
+
+if [ X${GDB} = X ] ; then
+  echo "Unable to find a GDB for @CPU_TARGET@ along your PATH"
+  exit 1
+fi
 
 test_exit()
 {
