2009-04-02	Joel Sherrill <joel.sherrill@OARcorp.com>
	* gdb-sim-run.in, gdb-sim.in: Add check_status.

diff --git a/sim-scripts/gdb-sim-run.in b/sim-scripts/gdb-sim-run.in
--- a/sim-scripts/gdb-sim-run.in
+++ b/sim-scripts/gdb-sim-run.in
@@ -53,6 +53,16 @@ warn() {
     [ "$1" ] && prerr $*
 }
 
+check_status()
+{
+  if [ $1 -ne 0 ] ; then
+    shift 
+    echo "FAILED: " "$*" >&2
+    exit 1
+  fi
+}
+
+
 #
 # process the options
 #
diff --git a/sim-scripts/gdb-sim.in b/sim-scripts/gdb-sim.in
--- a/sim-scripts/gdb-sim.in
+++ b/sim-scripts/gdb-sim.in
@@ -60,6 +60,15 @@ warn() {
     [ "$1" ] && prerr $*
 }
 
+check_status()
+{
+  if [ $1 -ne 0 ] ; then
+    shift 
+    echo "FAILED: " "$*" >&2
+    test_exit 1
+  fi
+}
+
 if [ $# -eq 0 ] ; then
   echo "No arguments .. no executable specified"
   exit 1 
