2009-09-24	Joel Sherrill <joel.sherrill@OARcorp.com>
	* gdb-sim-run.in, qemu-rtems.in, skyeye-support, smdk2410.in: Add more
	general support for rerunning a test which does not appear to have
	produced a complete set of coherent output.

diff --git a/sim-scripts/gdb-sim-run.in b/sim-scripts/gdb-sim-run.in
--- a/sim-scripts/gdb-sim-run.in
+++ b/sim-scripts/gdb-sim-run.in
@@ -255,6 +255,18 @@ catLog()
   echo
 }
 
+get_tname()
+{
+  echo $1 | grep "exe$" >/dev/null
+  if [ $? -eq 0 ] ; then
+    ext=.exe
+  else
+    ext=.ralf
+  fi
+  tfile=`basename $1`
+  echo `basename $tfile ${ext}`
+}
+
 runtest()
 {
   testname=${1}
@@ -274,13 +286,7 @@ runtest()
 
   echo Running ${testname} for maximum ${max_run_time} seconds
   echo $testname | grep "exe$" >/dev/null
-  if [ $? -eq 0 ] ; then
-    ext=.exe
-  else
-    ext=.ralf
-  fi
-  tfile=`basename $testname`
-  tname=`basename $tfile ${ext}`
+  tname=`get_tname $testname`
 
   logfile=${logdir}/${tname}
 
@@ -414,24 +420,25 @@ do
   test ${verbose} = "yes" && \
     echo BACKGROUND runtest ${toRun} ${testtype} ${limit}
   runtest ${toRun} ${testtype} ${limit}
-  if [ ${coverage} = "yes" ] ; then
-
-    # some simulators do not always write a coverage file with non-zero length
-    # If we see this, try again
-    if [ ${bspWritesZeroCoverage} = "yes" ] ; then
-      while [ ${coverage} = "yes" -a ! -s ${toRun}.cov ]
-      do
-        echo Rerunning ${toRun} due to zero length coverage file
-        runtest ${toRun} ${testtype} ${limit}
-      done
+  # Some simulators fail to work correctly all the time.  If this is one AND
+  # the run looks like it did not work right, then run again until it does
+  if [ ${bspRunsFailRandomly} = "yes" ] ; then
+    tries=1
+    while [ `bspCheckRunWasOK` -eq 1 -a ${tries} -lt 3 ]
+    do
+      tries=`expr ${tries} + 1`
+      echo "Rerunning ${toRun} due to random run failure (try=${tries})"
+      runtest ${toRun} ${testtype} ${limit}
+    done
+    if [ ${tries} -eq 3 ] ; then
+      echo "WARNING ${toRun} does not look like it had any output"
     fi
+  fi
 
-    # some BSPs produce trace oriented files which need to be converted
-    # to object coverage maps
-    if [ ${bspNeedsTraceConversion} = "yes" ] ; then
-      convertTraceToCoverageMap ${toRun}
-    fi
-
+  # some BSPs produce trace oriented files which need to be converted
+  # to object coverage maps
+  if [ ${bspNeedsTraceConversion} = "yes" ] ; then
+    convertTraceToCoverageMap ${toRun}
   fi
 
 
