pc386.in - qemu may now be named qemu-system-i386

diff --git a/sim-scripts/pc386.in b/sim-scripts/pc386.in
--- a/sim-scripts/pc386.in
+++ b/sim-scripts/pc386.in
@@ -5,7 +5,19 @@
 bspUsesGDBSimulator="no"
 runBSP=NOT_OVERRIDDEN
 if [ ! -r ${runBSP} ] ; then
-  runBSP=qemu
+  runBSP=notset
+  for name in qemu-system-i386 qemu
+  do
+    type ${name} >/dev/null 2>&1
+    if [ $? -eq 0 ] ; then
+      runBSP=${name}
+      break
+    fi
+  done
+  if [ ${runBSP} = "notset" ] ; then
+    echo "CANNOT FIND qemu or qemu-system-i386"
+    exit 1
+  fi
 fi
 bspNeedsDos2Unix="yes"
 bspRunsFailRandomly="yes"
